// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AnimeController from "./anime_controller";
application.register("anime", AnimeController);

import ChartController from "./chart_controller";
application.register("chart", ChartController);

import DimmerController from "./dimmer_controller";
application.register("dimmer", DimmerController);

import FileFormController from "./file_form_controller";
application.register("file-form", FileFormController);

import FlashController from "./flash_controller";
application.register("flash", FlashController);

import ModalController from "./modal_controller";
application.register("modal", ModalController);

import PopupController from "./popup_controller";
application.register("popup", PopupController);

import RateController from "./rate_controller";
application.register("rate", RateController);

import ScrollController from "./scroll_controller";
application.register("scroll", ScrollController);

import SidebarController from "./sidebar_controller";
application.register("sidebar", SidebarController);

import SwiperController from "./swiper_controller";
application.register("swiper", SwiperController);

import TransitionController from "./transition_controller";
application.register("transition", TransitionController);

import TrixController from "./trix_controller";
application.register("trix", TrixController);
