FROM ruby:3.0.2-alpine AS base
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
ENV RAILS_ENV production
ARG ENV_FILE
WORKDIR /usr/src/coffee-oma
COPY Gemfile Gemfile.lock package.json yarn.lock ./
RUN apk  --no-cache add linux-headers\
                        make\
                        gcc\
                        libc-dev\
                        nodejs\
                        tzdata\
                        mysql-client \
                        mysql-dev \
                        git \
                        curl \
                        imagemagick \
                        yarn &&\
    apk add --virtual build-dependencies --no-cache build-base curl-dev libxml2-dev
