source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '7.0.4.2'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.4.4'
# Use Puma as the app server
gem 'puma', '~> 4.3'
# Use SCSS for stylesheets
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbo-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
gem 'net-smtp'
gem 'redis', '~> 4.0'
gem 'redis-rails'
gem 'vite_rails'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'activeadmin', '~> 2.13'
gem 'acts-as-taggable-on', '~> 9.0'
gem 'aws-sdk-rails', '~> 3'
gem 'bootsnap', '>= 1.12', require: false
gem 'bootstrap', '~> 4.3.1'
gem 'carrierwave', '~> 2.2.0'
gem 'counter_culture', '~> 3.0'
gem 'daemons'
gem 'delayed_job_active_record'
gem 'devise'
gem 'devise-async'
gem 'devise-i18n'
gem 'devise-i18n-views'
gem 'dotenv-rails'
gem 'draper'
gem 'faker', git: 'https://github.com/faker-ruby/faker.git', branch: 'main'
gem 'fog-aws'
gem 'gimei'
gem 'gon'
gem 'gretel'
gem 'html2slim'
gem 'kaminari'
gem 'lograge'
gem 'logstash-event'
gem 'meta-tags'
gem 'mini_magick'
gem 'rack-cors'
gem 'rails-i18n'
gem 'ransack'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'rename'
gem 'semantic-ui-sass', '~> 2.4'
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'sitemap_generator'
gem 'slim'
gem 'slim-rails'
gem 'stimulus-rails'
gem 'view_component'
gem 'whenever', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'capybara'
  gem 'factory_bot_rails'
  gem 'launchy'
  gem 'pry-rails'
  gem 'rack-mini-profiler', require: false
  gem 'rspec_junit_formatter'
  gem 'rspec-rails'
  gem 'rubocop', '~> 1.30', require: false
  gem 'rubocop-performance'
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec'
  gem 'selenium-webdriver'
  gem 'spring-commands-rspec'
  gem 'webmock'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'annotate'
  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'brakeman', require: false
  gem 'bullet'
  gem 'foreman'
  gem 'letter_opener_web'
  gem 'solargraph'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'codecov', require: false
  gem 'simplecov', require: false
  gem 'simplecov-cobertura'
  gem 'test-prof', '~> 1.0'
end
